#pragma once
#include "AutoGeneratedSharedOrStaticLibExports.hpp"

namespace Code::SharedOrStaticLib
{

SHARED_OR_STATIC_LIB_API void DoPublicTask();

} // ~namespace Code::SharedOrStaticLib
